### PR TITLE
Sort branch

### PR DESCRIPTION
**Pull request by Addis-Belete**
we asked to solve the bubble-sort algorithm. we used the yield and block passing method to solve the algorithm.

### CODE REVIEW

**Comment by mimipeshy** [comment]
#### STATUS: APPROVED :dancing_women: :partying_face:
Hello team @Addis0943 and @chasscepts   👋🏾 👋🏾 great job on this project

#### Highlights :white_check_mark: :white_check_mark:

- [ ]  Well written README file, simple to follow and understand
- [ ]  Clean well written code

However, before marking the project as complete please fix the following

- [ ] Incoropate rubocop linters on your project. You can find [setup instructions](https://github.com/microverseinc/linters-config/tree/master/ruby)
- [ ] You don't need Rspec testing at this point you will come back to it in the next milestones. So check on it

That's all :smile: kindly submit another review when done.

_Feel free to reach out to me on slack if you have any questions or something is unclear, or just comment on this PR and tag my name  (@mimipeshy) and I will be glad to help_
Regards
Peris Ndanu

Regards
Peris Ndanu

**Comment by mimipeshy** [comment]
#### STATUS: CHANGES REQUIRED 🔴 ♻️ 
Hello team @Addis0943 and @chasscepts   👋🏾 👋🏾 great job on this project

#### Highlights :white_check_mark: :white_check_mark:

- [ ]  Clean well written code

However, before marking the project as complete please fix the following

- [x] Incorporate rubocop linters on your project. You can find [setup instructions](https://github.com/microverseinc/linters-config/tree/master/ruby)
- [x] You don't need Rspec testing at this point you will come back to it in the next milestones. So, remove any Rspec files you have. The tests are failing
- [x] In your README file, in the getting started section, after `cd Bubble_sort` in the next bullet point add the command on how to run your project

That's all :smile: kindly submit another review when done.

_Feel free to reach out to me on slack if you have any questions or something is unclear, or just comment on this PR and tag my name  (@mimipeshy) and I will be glad to help_
Regards
Peris Ndanu

Regards
Peris Ndanu

**Comment by Addis-Belete** [comment]
Thank you for your feedback. We fixed all the feedbacks.
kindly review and approve it, please.

**Review by andresporras3423 — APPROVED** [review]
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:
**Hello Francis Obetta & Addis Bejiga** 
Amazing job :tada: :tada: :tada:  you have met all the requirements for this project
Now you are ready to continue with your next challenge :muscle: 
Don't forget to merge with the master branch
 
Keep going like this  :clap: :clap:
 
Oscar Andrés Russi Porras

**Pull request merged**
